### ISSUE TITLE
Checklist: normalise topics

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/csharp#1273]
**Note**: the suggestions are generated automagically. If something is _actually_ missing, please open an issue at [problem-specifications](https://github.com/exercism/problem-specifications) to add the missing topics.

```
=> fetching config from ../exercism-csharp/config.json
=> reading topics from ..\problem-specifications\TOPICS.txt
```

<details>
  <summary>List of valid topics</summary>

  - `abstract_classes`
  - `callbacks`
  - `conditionals`
  - `events`
  - `equality`
  - `exception_handling`
  - `generics`
  - `inheritance`
  - `interfaces`
  - `loops`
  - `operator_overloading`
  - `pattern_matching`
  - `polymorphism`
  - `recursion`
  - `threading`
  - `type_conversion`
  - `variables`
  - `arrays`
  - `booleans`
  - `classes`
  - `dates`
  - `discriminated_unions`
  - `enumerations`
  - `floating_point_numbers`
  - `graphs`
  - `integers`
  - `lists`
  - `maps`
  - `matrices`
  - `optional_values`
  - `queues`
  - `records`
  - `sequences`
  - `sets`
  - `stacks`
  - `strings`
  - `structs`
  - `time`
  - `trees`
  - `tuples`
  - `algorithms`
  - `bitwise_operations`
  - `concurrency`
  - `cryptography`
  - `domain_specific_languages`
  - `files`
  - `filtering`
  - `games`
  - `globalization`
  - `logic`
  - `math`
  - `memory_management`
  - `networking`
  - `parallelism`
  - `parsing`
  - `pattern_recognition`
  - `performance`
  - `randomness`
  - `refactoring`
  - `regular_expressions`
  - `searching`
  - `security`
  - `sorting`
  - `text_formatting`
  - `transforming`
  - `behavior_driven_development`
  - `functional_programming`
  - `object_oriented_programming`
  - `reactive_programming`
  - `test_driven_development`
</details>

## Exercises with non-standard topics

- [ ] [`leap`](https://github.com/exercism/csharp/tree/master/exercises/leap)
  Incorrect topics:
  - [ ] `control_flow_if_else_statements`
- [ ] [`nucleotide-count`](https://github.com/exercism/csharp/tree/master/exercises/nucleotide-count)
  Incorrect topics:
  - [ ] `dictionaries`
- [ ] [`clock`](https://github.com/exercism/csharp/tree/master/exercises/clock)
  Incorrect topics:
  - [ ] `structural_equality` (perhaps: `equality`)
- [ ] [`bob`](https://github.com/exercism/csharp/tree/master/exercises/bob)
  Incorrect topics:
  - [ ] `control_flow_if_else_statements`
- [ ] [`accumulate`](https://github.com/exercism/csharp/tree/master/exercises/accumulate)
  Incorrect topics:
  - [ ] `extension_methods`
- [ ] [`collatz-conjecture`](https://github.com/exercism/csharp/tree/master/exercises/collatz-conjecture)
  Incorrect topics:
  - [ ] `control_flow_conditionals` (perhaps: `conditionals`)
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`difference-of-squares`](https://github.com/exercism/csharp/tree/master/exercises/difference-of-squares)
  Incorrect topics:
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`etl`](https://github.com/exercism/csharp/tree/master/exercises/etl)
  Incorrect topics:
  - [ ] `dictionaries`
- [ ] [`pythagorean-triplet`](https://github.com/exercism/csharp/tree/master/exercises/pythagorean-triplet)
  Incorrect topics:
  - [ ] `overloading` (perhaps: `threading`)
- [ ] [`word-count`](https://github.com/exercism/csharp/tree/master/exercises/word-count)
  Incorrect topics:
  - [ ] `dictionaries`
- [ ] [`pascals-triangle`](https://github.com/exercism/csharp/tree/master/exercises/pascals-triangle)
  Incorrect topics:
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`roman-numerals`](https://github.com/exercism/csharp/tree/master/exercises/roman-numerals)
  Incorrect topics:
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`binary-search-tree`](https://github.com/exercism/csharp/tree/master/exercises/binary-search-tree)
  Incorrect topics:
  - [ ] `overloading` (perhaps: `threading`)
- [ ] [`parallel-letter-frequency`](https://github.com/exercism/csharp/tree/master/exercises/parallel-letter-frequency)
  Incorrect topics:
  - [ ] `dictionaries`
  - [ ] `parallellism` (perhaps: `parallelism`)
- [ ] [`bowling`](https://github.com/exercism/csharp/tree/master/exercises/bowling)
  Incorrect topics:
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`alphametics`](https://github.com/exercism/csharp/tree/master/exercises/alphametics)
  Incorrect topics:
  - [ ] `dictionaries`
- [ ] [`rest-api`](https://github.com/exercism/csharp/tree/master/exercises/rest-api)
  Incorrect topics:
  - [ ] `json` (perhaps: `loops`, `lists`, `maps`, `sets`, `time`, `math`, `events`, `dates`, `trees`, `files`, `games`, `logic`, `parsing`, `sorting`)

## Exercises without topics

- [ ] [`binary`](https://github.com/exercism/csharp/tree/master/exercises/binary)
- [ ] [`trinary`](https://github.com/exercism/csharp/tree/master/exercises/trinary)
- [ ] [`octal`](https://github.com/exercism/csharp/tree/master/exercises/octal)
- [ ] [`hexadecimal`](https://github.com/exercism/csharp/tree/master/exercises/hexadecimal)
