### ISSUE TITLE
[v3] Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#1482]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [ ] [Configure online editor](https://github.com/exercism/csharp/issues/1473)
- [ ] [Add key features](https://github.com/exercism/csharp/issues/1474)
- [ ] [Add tags](https://github.com/exercism/csharp/issues/1475)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/csharp/issues/1476)
- [ ] [Update status of track](https://github.com/exercism/csharp/issues/1480)
- [ ] [Update status of Concept Exercises](https://github.com/exercism/csharp/issues/1481)
- [ ] [Pass linting checks](https://github.com/exercism/csharp/issues/1477)
- [ ] [Build Test Runner](https://github.com/exercism/csharp/issues/1478)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/csharp/issues/1479) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7
